# Basic Information 
title: Martin Weyssow
position: Research Scientist (Postdoc)
affiliation: Singapore Management University
affiliation_link: https://computing.smu.edu.sg
affiliation_logo: 
email: mweyssow (at) smu.edu.sg

# Search Engine Optimization (SEO)
keywords: martin, weyssow, martinwey, martin-wey
canonical: https://martin-wey.github.io/
description: Martin Weyssow is a Research Scientist (postdoc) at Singapore Management University (SMU). His research lies in deep learning, natural language processing and software engineering.

# The option is used to enable the Johns Hopkins template.
enable_hopkins_logo: false

# The option is used to show the last update time.
enable_last_update: false

# Links
link_type: text #text/icon
google_scholar: https://scholar.google.com/citations?user=VOViiCUAAAAJ
cv_link: ./assets/martin_weyssow_cv.pdf
github_link: https://github.com/martin-wey
linkedin: https://www.linkedin.com/in/martin-weyssow/
twitter: https://twitter.com/MWeyssow

# Images 
avatar: ./assets/img/IMG_5755.jpg
favicon: ./assets/img/favicon.png
favicon_dark: ./assets/img/favicon-dark.png

# Footnotes
footnote: 
footnote_link:

# Analytics
# Please remove the following lines about analytics services if you fork my project. 
# Otherwise, the analytics information of your website will be recorded to my ClustrMaps accounts.
clustrmaps_id: 

# The following files will be removed from the generated website.
exclude:
  - build.sh
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE
  - CNAME
